ALTER TABLE "Request" ADD COLUMN IF NOT EXISTS "budgetMinCents" INTEGER;
ALTER TABLE "Request" ADD COLUMN IF NOT EXISTS "budgetMaxCents" INTEGER;
ALTER TABLE "QuoteRequest" ADD COLUMN IF NOT EXISTS "budgetMinCents" INTEGER;
ALTER TABLE "QuoteRequest" ADD COLUMN IF NOT EXISTS "budgetMaxCents" INTEGER;
