const fs=require('fs/promises'),os=require('os'),path=require('path'),{spawn}=require('child_process');
const sharp=require(process.cwd()+'/node_modules/sharp');
(async()=>{const repo=process.cwd(),root=await fs.mkdtemp(path.join(os.tmpdir(),'thumbnail-watch-'));let child,log='';
const pause=ms=>new Promise(r=>setTimeout(r,ms));const wait=async(fn,label)=>{const end=Date.now()+30000;while(Date.now()<end){if(await fn())return;await pause(150)}throw new Error('Timed out: '+label+'\n'+log)};
try{
await fs.mkdir(path.join(root,'scripts/thumbnails'),{recursive:true});await fs.mkdir(path.join(root,'public'));await fs.mkdir(path.join(root,'app'));await fs.mkdir(path.join(root,'data'));
await fs.symlink(path.join(repo,'node_modules'),path.join(root,'node_modules'),'dir');
for(const p of ['scripts/dev-with-thumbnails.mjs','scripts/generate-thumbnails.ts','scripts/thumbnails/engine.mjs'])await fs.copyFile(path.join(repo,p),path.join(root,p));
await fs.writeFile(path.join(root,'package.json'),JSON.stringify({name:'thumbnail-watch-fixture',version:'1.0.0'}));
await fs.writeFile(path.join(root,'app/layout.js'),"export default function Layout({children}){return <html><body>{children}</body></html>}");await fs.writeFile(path.join(root,'app/page.js'),"export default function Page(){return <p>watch fixture</p>}");
await fs.writeFile(path.join(root,'scripts/thumbnails/catalog.ts'),"import sources from '../../data/assets.json';export default sources;");
const first={id:'test.first',src:'/first.png',profile:'preview'};await fs.writeFile(path.join(root,'data/assets.json'),JSON.stringify([first]));
await sharp({create:{width:32,height:16,channels:3,background:'red'}}).png().toFile(path.join(root,'public/first.png'));
child=spawn(process.execPath,['scripts/dev-with-thumbnails.mjs','--port','3059'],{cwd:root});child.stdout.on('data',d=>log+=d);child.stderr.on('data',d=>log+=d);
await wait(()=>Promise.resolve(log.includes('Ready in')),'port forwarded startup');if(!log.includes('3059'))throw new Error('Port not forwarded');
const read=async()=>JSON.parse(await fs.readFile(path.join(root,'src/lib/thumbnails/manifest.generated.json'),'utf8'));
const before=await read();await sharp({create:{width:32,height:16,channels:3,background:'blue'}}).png().toFile(path.join(root,'public/first.png'));
await wait(async()=> (await read()).sourceKeys['test.first']!==before.sourceKeys['test.first'],'source change');
const second={id:'test.second',src:'/new/second.png',profile:'icon'};
await fs.writeFile(path.join(root,'data/assets.json'),JSON.stringify([first,second]));await wait(()=>Promise.resolve(log.includes('Thumbnail refresh failed')),'failed addition retains manifest');
if((await read()).entries['test.second'])throw new Error('Invalid manifest published');
await fs.mkdir(path.join(root,'public/new'));await sharp({create:{width:20,height:20,channels:3,background:'green'}}).png().toFile(path.join(root,'public/new/second.png'));
await wait(async()=>!!(await read()).entries['test.second'],'new directory/source recovery');
await fs.writeFile(path.join(root,'data/assets.json'),JSON.stringify([first]));await wait(async()=>!(await read()).entries['test.second'],'remove registration');
const failures = (log.match(/Thumbnail refresh failed/g)||[]).length;
await fs.writeFile(path.join(root,'scripts/thumbnails/catalog.ts'),"import sources from './future';export default sources;");
await wait(()=>Promise.resolve((log.match(/Thumbnail refresh failed/g)||[]).length>failures),'missing metadata module');
await fs.writeFile(path.join(root,'scripts/thumbnails/future.ts'),'export default '+JSON.stringify([first,second])+';');
await wait(async()=>!!(await read()).entries['test.second'],'new metadata module recovery');
child.kill('SIGTERM');await wait(()=>Promise.resolve(child.exitCode!==null),'child cleanup');await wait(()=>fetch('http://localhost:3059').then(()=>false,()=>true),'Next stopped');
console.log('PASS: port forwarding, registered source edits, new metadata dependency, failure-safe missing source, new-directory recovery, removal, missing metadata module recovery, child shutdown');
}finally{if(child&&child.exitCode===null)child.kill('SIGKILL');await fs.rm(root,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1});
