PRAGMA foreign_keys=OFF;

CREATE TABLE IF NOT EXISTS "PendantStyle" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "slug" TEXT NOT NULL UNIQUE,
  "label" TEXT NOT NULL,
  "src" TEXT NOT NULL,
  "accent" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

PRAGMA foreign_keys=ON;
